Include DM particles information in NTuples.
rjwang/DMHiggsAnalysis pull request #31
Opened 2016-10-14 15:23 UTC by alopezso

2016-10-14 15:34 UTC, rjwang requested changes
there are several changes which are not relevant to the addition of generator level, please go to clean them.

2016-10-14 15:34 UTC, rjwang commented on data/DMHiggsAnalysis.cfg
> +NTupleName:	  ggH125_gamgam.NTuple.root
what is this for ?

2016-10-14 15:34 UTC, rjwang commented on Root/DMHiggsAnalysis.cxx
> +bool DMHiggsAnalysis::isTruthHiggsPhoton(const xAOD::TruthParticle* truth){
this function has nothing inside, do we need to add?

2016-10-14 15:34 UTC, rjwang commented on Root/DMHiggsAnalysis.cxx
> +    m_isMxAOD=false;
I don't think we need this, when adding the gen-level information, we are always running on mXAOD

2016-10-14 15:38 UTC, alopezso commented on data/DMHiggsAnalysis.cfg
> +NTupleName:	  ggH125_gamgam.NTuple.root
The problem is that DM particles are not added on MxAOD. So, everything needs to be done on DxAODs. But f you run on MxAODs, the inputfile name won't be sample name but something of style DAOD_HIGGS1..... So we need to include in data/DMHiggsAnalysis.cfg the output NTuple name and not derive it from the inputName

2016-10-14 15:39 UTC, alopezso commented on Root/DMHiggsAnalysis.cxx
> +bool DMHiggsAnalysis::isTruthHiggsPhoton(const xAOD::TruthParticle* truth){
No, I added it from a previous code but forgot to eliminate it

2016-10-14 15:39 UTC, alopezso commented on Root/DMHiggsAnalysis.cxx
> +    m_isMxAOD=false;
Yes, we need it because of what I said in previous comment

2016-10-14 15:58 UTC, alopezso commented on Root/DMHiggsAnalysis.cxx
> +bool DMHiggsAnalysis::isTruthHiggsPhoton(const xAOD::TruthParticle* truth){
I have just eliminate it and did another commit. It is inside the pull request

2016-10-14 17:30 UTC, rjwang commented on data/DMHiggsAnalysis.cfg
> +NTupleName:	  ggH125_gamgam.NTuple.root
okay, if I only run MxAODs, is there a way to get the gen_MET ?

2016-10-14 17:34 UTC, alopezso commented on data/DMHiggsAnalysis.cfg
> +NTupleName:	  ggH125_gamgam.NTuple.root
Yes, getting truth MET either accessing through the truthHandler or directly on the containers or HGamVariables. This met was estimated with all non-interacting particles, not just DM particles.

2016-10-14 17:37 UTC, rjwang commented on data/DMHiggsAnalysis.cfg
> +NTupleName:	  ggH125_gamgam.NTuple.root
okay, then I understand the situation, just to double check, if you run on MxAOD, get the genMET from  all non-interacting particles. And the same signal sample, but DxAODs, get the genMET from DM particles, are the two plots same ?

2016-10-14 17:37 UTC, rjwang commented on Root/DMHiggsAnalysis.cxx
> +    m_isMxAOD=false;
okay, i see

2016-10-23 14:11 UTC, rjwang commented
what is the status of adding the genMET now?

2016-10-24 08:22 UTC, alopezso commented
Hi ! I have just done this commit : https://github.com/rjwang/DMHiggsAnalysis/pull/31/commits/544fedc5e065bc6df527298f113f43fa7436a141

2016-10-24 08:36 UTC, rjwang commented
this commit adds both ways retrieve the gen-level information?  One is from DAOD, one is from MxAOD, they are not working at the same time, right ? If this is true, please keep only the way from MxAOD, totally remove the one from DAOD.

2016-10-25 09:01 UTC, alopezso commented
Hi Renjie,
Sorry for answering so late but I was doing the MxAODSys and couldn't test the DMHiggsAnalysis. However, I think that if you want that, you could just reject the pull request, since it only uses MxAOD.

2016-10-26 19:21 UTC, rjwang commented
I am closing this pull request, please go to add a new one ONLY with gen MET running on MxAOD

2016-10-26 19:21 UTC, closed without merging